name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -s "https://xhdqfglkfgfyuqibdiam.supabase.co/auth/v1/health" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZHFmZ2xrZmdmeXVxaWJkaWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1NDU0MTYsImV4cCI6MjA5NzEyMTQxNn0.nnHEd8lHt5m-i27UJcJUsgRHpBzyhEPdADe1kuZ2Pq0"
